version: 0.0
os: windows
files:
  - source: /
    destination: /home/ubuntu/Django_Chat_Application
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/supervisorStart.sh
      timeout: 300
      runas: root
